---
title: 'Fitting ODEs with CmdStanPy'
author: 'Craig Fouts (adapted from [*Fitting ODEs in Stan*](https://github.com/tah17/fitting-odes-stan-walkthrough))'
date: '`r Sys.Date()`'
output:
    html_document:
        includes:
            in_header: header.html
        number_sections: true
        toc: true
        toc_float: true
bibliography: references.bib
---

# Introduction

This article intended to be a guide for fitting Ordinary Differential Equation (ODE) models using Python and Stan via CmdStanPy (a Python interface to CmdStan), where Stan is a probabilistic programming language for performing Bayesian inference and CmdStan is its command line interface. Often, when modelling, we want to be able to quantify the uncertainty of our estimates. Bayesian inference allows us to do this in a principled manner for ODE models. All technical details mentioned here closely follow the [Stan](https://mc-stan.org/docs/stan-users-guide/) [@stan2025] user manual and Bayesian Data Analysis textbook [@gelman2013]. For a more detailed explanation on modelling with Stan, please refer to the [Stan](https://mc-stan.org/docs/) and [CmdStanPy](https://mc-stan.org/cmdstanpy/) documentation.

Before going through the example, let's import the relevant libraries and set a random seed.

```{python, results='hide'}
import cmdstanpy
import matplotlib.pyplot as plt
import numpy as np
import pyreadr
from cmdstanpy import CmdStanModel
from IPython.display import Markdown
cmdstanpy.install_cmdstan();
```

```{python}
seed = 739485
rng = np.random.default_rng(seed)
```

The example in this article is about fitting a simple logistic ODE to some pre-generated fake data. Below, we'll discuss how the ODE is defined ([The Model]), what the fake data looks like ([The Data]), how to fit the model to the data ([Model Fitting]), how to check the model fit for convergence ([Checking Model Fit]), and how to visualise the estimated parameterisation ([Plotting Model Fit] and [Estimating Parameters]).

# The Model

The logistic growth model is a popular autonomous one-dimensional ODE often used for modelling populations over time:

$$
\frac{dz}{dt} \, = \, f \left( z \right) \, = \, \rho \, z \, \left( 1 - \frac{z}{\kappa} \right)
$$

The mean population, $z(t)$, grows over time, $t$, at a growth rate of $\rho$. Growth slows as the population reaches its theoretical limit, $\kappa$, often called the **carrying capacity**.

# The Data

The fake data (provided in `data/data.Rda`) was actually generated using our logistic model. That being said, for the purposes of this example, we will imagine the data, $y$, is the concentration of some population growing over time, $t$, that has been recorded in an experiment in which we assume some observational noise has been introduced during data collection. The aim is to fit the logistic ODE to this collected data, estimate important parameter values (like the growth rate, $\beta$), and to quantify the uncertainty of our estimates.

## Visualisation

First, let's read in the data from `data/data.Rda`:

```{python}
df = pyreadr.read_r('data/data.Rda')[None]
Markdown(df.head().to_markdown(index=False, numalign='center', floatfmt='.6f'))
```

Let's plot the data to see what it looks like:

```{python, fig.align='center'}
t = df['time']
fig, ax = plt.subplots(figsize=(8, 4))
ax.grid(alpha=.5)
ax.scatter(t, df['y'], s=100, zorder=2)
ax.set_xlabel('Time')
ax.set_ylabel(ylabel='y', rotation=0.)
fig.tight_layout()
```

## Pre-Processing

Next, we'll have to create a custom data object since Stan expects a particular format:

```{python}
# Only want to solve the ODE at unique time points to reduce runtime
time_pts = np.sort(t.unique())

# Dictionary of data corresponding to the model definition in 'cmdstanpy.stan'
stan_data = {
    'N': len(df),
    'T': len(time_pts),
    'y': df['y'].to_numpy(),
    't': time_pts,
    't_idx': [np.where(time_pts == t)[0].item() + 1 for t in df['time']],
    'include_likelihood': True
}
```

Although not relevant to this example, even if there are multiple observations at a single time point (e.g., multiple replicates), the ODE is only solved once, so our dictionary is set up to reflect this.

# Model Fitting{.tabset}

## Python Code

To fit the logistic ODE using Stan, a `.stan` file needs to be created such that we can define the model. For this example, one has already been provided in `model.stan`. A copy of the file can also be found under the "Stan Code" tab so we can easily refer back to the relevant sections of the Stan model.

In our `.stan` file, the desired likelihood and any necessary priors can be specified. One of the simplest **likelihoods** is a Gaussian, where we assume our data $y_t$ at time $t$ is normally distributed about the ODE solution, $z(t)$, with noise scaled by $\sigma$:

$$
y_t \sim \text{N} \left( z(t), \, \sigma \right)
$$

In `model.stan`, this is written in the `model` block as follows:

```
y ~ normal(z[t_idx, 1], S);
```

We also assume the following **priors**:

$$
\begin{align*}
    y_0 &\sim \text{N}^+ \left(0, \, 1 \right) \\
    \sigma &\sim \text{N}^+ \left(0, \, 1 \right) \\
    \rho &\sim \text{N}^+ \left(0, \, 1 \right) \\
    \kappa &\sim \text{N}^+ \left(10, \, 1 \right)
\end{align*}
$$

These are similarly specified in the `model` block:

```
y0 ~ std_normal();
S ~ std_normal();
R ~ std_normal();
K ~ normal(10, 1);
```

These priors are chosen somewhat arbitrarily for this example, but prior choise is important! Further information on choosing priors can be found in [@gelman2013] and [@gelman2020].

Finally, to fit the model, we need only run the following commands:

```{python, results='hide'}
model = CmdStanModel(stan_file='model.stan')
fit = model.sample(stan_data, chains=4, seed=seed)
```

Here, the output is hidden as it is quite long, but Stan will output progress bars for sampling from the posterior along each chain, with the time taken for sampling given at the end. Any warnings about convergence will also be given here.

## Stan Code

Below is a copy of the `model.stan` file used to define our logistic ODE, the fitting procedure for which can be found under the "Python Code" tab. It specifies the model with six different "blocks": (**1**) `functions`, where the ODE itself is specified, (**2**) `data`, where the input data is specified (notice how the keys in our `data` dictionary match the variable names in this block), (**3**) `parameters`, for the free parameters of the model, (**4**) `transformed parameters`, where we (approximately) solve the ODE, (**5**) `model`, that specifies the likelihood and priors, and (**6**) `generated quantities`, where we simulate ODE solutions and draw samples from the fitted model.

```
functions {
    vector f(real t, vector z, real R, real K) {
        vector[1] dz_dt;

        dz_dt[1] = R*z[1]*(1 - z[1]/K);

        return dz_dt;
    }
}

data {
    int<lower=0> N;  // Number of data points
    int<lower=0> T;  // Number of time points
    vector[N] y;  // Input data
    array[T] real t;  // Time points
    array[N] int<lower=1, upper=T> t_idx;  // Time index for each data point
    int<lower=0, upper=1> include_likelihood;
}

parameters {
    real<lower=0> y0;  // Initial condition
    real<lower=0> S;  // Noise scale
    real<lower=0> R;  // Growth rate
    real<lower=0> K;  // Carrying capacity
}

transformed parameters {
    array[T] vector[1] z;

    z[1, 1] = y0;
    z[2:T, 1] = ode_rk45(f, z[1,], t[1], t[2:T], R, K)[,1];
}

model {
    y0 ~ std_normal();
    S ~ std_normal();
    R ~ std_normal();
    K ~ normal(10, 1);

    if (include_likelihood)
        y ~ normal(z[t_idx, 1], S);
}

generated quantities {
    array[N] real z_rep = z[t_idx, 1];  // Posterior samples of ODE solution
    array[N] real y_rep = normal_rng(z_rep, S);  // Posterior predictive
}
```

# Checking Model Fit

In the above `model.sample(...)` method call, the keyword argument `chains=4` was set to specify that we want to run four chains independently. This is mainly done so we can assess if the chains have converged to the same and (what we assume to be) true posterior distribution.

In reality, we cannot know if the chains have converged to the true posterior, as we do not know what the true posterior is. Instead, signs of non-convergence are monitored. One way to do this is by plotting the posterior sample draws over iterations for each chain (i.e., a **trace plot**) to make sure the chains are well **mixed** and **stationary**. The chains should all converge to the same posterior (i.e., be well *mixed*) and they should actually converge to a distribution and stay there (i.e., be *stationary*) [@gelman2013]. If the chains are not well mixed or stationary (e.g., if the chains' sampling paths appear to be completely distinct or drift), these are signs of non-convergence and samples taken from these chains should not be used further.

```{python, fig.align='center'}
params = ('y0', 'S', 'R', 'K')
n_draws = len(draws := fit.draws_pd())
n_chains = len(draws['chain__'].unique())
fig, axes = plt.subplots(round(len(params)/2), 2, figsize=(8, 4))

for ax, param in zip(axes.flatten(), params):
    ax.grid(alpha=.5)
    param_draws = draws[param].to_numpy().reshape(n_draws//n_chains, n_chains)
    lines = ax.plot(param_draws, alpha=.5, linewidth=.5)
    ax.set(title=param, xlabel='Draw')

fig.legend(lines, np.arange(n_chains), title='chain', bbox_to_anchor=(1.08, .68))
fig.tight_layout()
```

The trace plots look okay. However, visual assessment can be subjective, so convergence is also assessed using the Gelman-Rubin metric, $\widehat{\, R}$ [@vehtari2021], which can be thought of as a numerical value summarising the above. Usually, a value of $\widehat{\, R}$ > 1.01 is used as a heuristic to diagnose lack of convergence.

```{python}
Markdown(fit.summary().head()[1:].to_markdown(numalign='center', floatfmt='.4f'))
```

The $\widehat{\, R}$ values listed in the last column of the table above look to be < 1.01!

# Plotting Model Fit

During fitting, it was assumed that each data point, $y_t$, is normally distributed about the ODE solution, $z(t)$, with some noise scaled by $\sigma$ at time $t$. Since there are no signs of non-convergence so far, we can plot posterior samples of $z(t)$ to see if they align with the mean of the data and thus check that our fitted model can at least visually capture the general trends of the data:

```{python, fig.align='center'}
z_keys = [f'z_rep[{i + 1}]' for i in range(stan_data['N'])]
sample_idx = rng.integers(0, n_draws, 100)
z = draws[z_keys].loc[sample_idx].T.to_numpy()
fig, ax = plt.subplots(figsize=(8, 4))
ax.grid(alpha=.5)
ax.plot(stan_data['t'], z, alpha=.5, linewidth=.5)
ax.scatter(t, df['y'], s=10, c='black', zorder=2)
ax.set_xlabel('Time')
ax.set_ylabel('z', rotation=0.)
fig.tight_layout()
```

Here, the lines are draws of the ODE solution, $z(t)$, that are obtained using samples from the posterior $p(\theta \, | \, y)$, and the dots show the data points, $y$, used to fit the model. 

We can also plot samples from the posterior predictive distribution, $p(y^\text{rep} \, | \, y)$, to check how well our entire model, with assumed priors and likelihood, fits the data [@gelman2013]:

$$
p(y^\text{rep} \, | \, y) = \int p(y^\text{rep} \, | \, \theta) p(\theta \, | \, y) d\theta
$$

The fit model should be able to generate data under the posterior predictive distribution that resembles the observed data [@gelman2013]:

```{python, fig.align='center'}
y_keys = [f'y_rep[{i + 1}]' for i in range(stan_data['N'])]
y = (y_draws := draws[y_keys].T.to_numpy()).mean(-1)
d = np.sort(np.sqrt(np.square((y_draws - y[:, None]))), -1)
levels, colors, fills = (.95, .8, .5), ('#e2c6a6', '#d1b150', '#d17d68'), []
fig, ax = plt.subplots(figsize=(8, 4))
ax.grid(alpha=.5)

for level, color in zip(levels, colors):
    h = d[:, round(level*d.shape[1])]
    fills.append(ax.fill_between(stan_data['t'], y - h, y + h, color=color, zorder=2))

ax.plot(stan_data['t'], y, linewidth=2., color='black')
ax.scatter(t, df['y'], s=10, c='black', zorder=2)
ax.set_xlabel('Time')
ax.set_ylabel('z', rotation=0.)
fig.legend(fills, levels, title='level', bbox_to_anchor=(1.12, .68))
fig.tight_layout()
```

Here, "level" refers to the $100 \times$ level % credible interval of the posterior predictive distribution. The fit looks good so far! For further information on visual checking of model fit, please refer to [@gabry2019] and [@gelman2020].

# Estimating Parameters

Once the model has been visually assessed as we did in the previous section, we can go ahead and visualise the posterior distribution of the parameters themselves. Since we have fit the model to its own fake data, we can also compare our inferred distributions to the true parameter values that were used to generate the fake data and thus check the validity of our parameter estimates:

```{python, results='hide', fig.aling='center'}
true_params = pyreadr.read_r('data/params.Rda')['params']
param_keys = [param for param in params if param in true_params][::-1]
fig, ax = plt.subplots(figsize=(8, 4))
ax.grid(alpha=.5)

for (i, param), color in zip(enumerate(param_keys), colors):
    param_mean, param_draws = fit.summary()['Mean'][param], draws[param]
    violin = ax.violinplot(param_draws, [i], orientation='horizontal', showextrema=False, side='high')
    violin['bodies'][0].set_facecolor(color)
    violin['bodies'][0].set_alpha(1.)
    violin['bodies'][0].set_zorder(2)
    d = np.argsort(np.sqrt(np.square((param_draws - param_mean))))
    level_50, level_95 = param_draws[d[:round(.5*len(draws))]], param_draws[d[:round(.95*len(draws))]]
    ax.plot(level_50, (i - .005)*np.ones_like(level_50), linewidth=3., color='#683f34')
    ax.plot(level_95, (i - .005)*np.ones_like(level_95), linewidth=1., color='#683f34')
    ax.scatter(param_mean, i, zorder=2, color='#683f34')
    param_value = true_params[param].item()
    ax.scatter(param_value, i, s=50, linewidths=2., facecolors='white', edgecolors='black', zorder=2)

ax.set_yticks(range(len(param_keys)), param_keys)
ax.set_xlabel('Value')
ax.set_ylabel('Parameter')
fig.tight_layout()
```

Here, the distributions of the parameter draws are shown (brown dots are means, thick lines are 50% credible intervals, and thin lines are 95% credible intervals) along with the true parameter values (white circles). It is a good check to verify that the estimated 95% credible intervals include the true parameter values.

I didn't include `K` above or save it in `params.Rmd` as its scale is completely different from the other parameters (making visualisation a bit difficult), but you can (with some modification to the code in the loop) add it to the `param_keys` line if you want to visualise the estimate.

# References
